/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mform;

import database.DataInserter;
import database.DataRetriever;
import java.util.List;
import mform.entity.DataPerkebunan;
import mform.form.FormDataPerkebunan;

/**
 *
 * @author USER
 */
public class kuesionerPanel4 extends javax.swing.JFrame {
    private String namaPetugas;
    private DataPerkebunan dataPerkebunan;
    /**
     * Creates new form MF_BlokV
     */
    public kuesionerPanel4(String namaPetugas, DataPerkebunan dataPerkebunan) {
        initComponents();
        this.namaPetugas = namaPetugas;
        this.dataPerkebunan = dataPerkebunan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        stok_pabrik_gulaTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stok_pedagangTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        stok_petaniTextField = new javax.swing.JTextField();
        simpanToggleButton = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        jToggleButton1.setText("NEXT");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Stok Pabrik Gula (Ton):");

        stok_pabrik_gulaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stok_pabrik_gulaTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Stok Pedagang (Ton):");

        stok_pedagangTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stok_pedagangTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Stok Petani (Ton):");

        stok_petaniTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stok_petaniTextFieldActionPerformed(evt);
            }
        });

        simpanToggleButton.setText("SIMPAN");
        simpanToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanToggleButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STOK GKP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(simpanToggleButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stok_pedagangTextField)
                                    .addComponent(stok_petaniTextField)
                                    .addComponent(stok_pabrik_gulaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok_pabrik_gulaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok_pedagangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok_petaniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanToggleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stok_pabrik_gulaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stok_pabrik_gulaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stok_pabrik_gulaTextFieldActionPerformed

    private void stok_pedagangTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stok_pedagangTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stok_pedagangTextFieldActionPerformed

    private void stok_petaniTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stok_petaniTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stok_petaniTextFieldActionPerformed

    private void simpanToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanToggleButtonActionPerformed
        // TODO add your handling code here:
        dataPerkebunan.getStokGKP().setStokPabrikGula(Double.parseDouble(stok_pabrik_gulaTextField.getText()));
        dataPerkebunan.getStokGKP().setStokPedagang(Double.parseDouble(stok_pedagangTextField.getText()));
        dataPerkebunan.getStokGKP().setStokPetani(Double.parseDouble(stok_petaniTextField.getText()));
        FormDataPerkebunan form = new FormDataPerkebunan();
        dataPerkebunan.getKeteranganPetugas().setNamaPencacah(namaPetugas);
        dataPerkebunan.getKeteranganPetugas().setNamaPemeriksa("NamaPemeriksaTest");
        form.setDataPerkebunan(dataPerkebunan);
        
        //Validate
        if(!form.validate()){
            System.out.println("Data invalid. Fix errors below:");
            List<String> errorMessages = form.getErrorMessages();
            for (String errorMessage : errorMessages) {
                System.out.println("- "+ errorMessage);
            }
        }else{
            // Memasukkan data ke dalam database
            System.out.println("MEMASUKKAN DATA KE DALAM DATABSE");
            DataInserter dataInserter = new DataInserter();
            dataInserter.insertData(dataPerkebunan);
            
            form.reset();
            
            //Mencoba mengambil data dari database
            System.out.println("MENGAMBIL DATA \"Perusahaan Tebu Sejahtera\" DARI DATABSE");
            DataRetriever dataRetriever = new DataRetriever();
            dataPerkebunan = dataRetriever.retrieveData("Perusahaan Tebu Sejahtera");
            form.setDataPerkebunan(dataPerkebunan);
            
            form.print();
        }
    }//GEN-LAST:event_simpanToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String namaPetugas = null;
        DataPerkebunan dataPerkebunan = null;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuesionerPanel4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuesionerPanel4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuesionerPanel4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuesionerPanel4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuesionerPanel4(namaPetugas, dataPerkebunan).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton simpanToggleButton;
    private javax.swing.JTextField stok_pabrik_gulaTextField;
    private javax.swing.JTextField stok_pedagangTextField;
    private javax.swing.JTextField stok_petaniTextField;
    // End of variables declaration//GEN-END:variables
}
