/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mform;

import mform.entity.DataPerkebunan;

/**
 * @author: Kelompok 2
 * 1. Alvin Jeremy Naiborhu
 * 2. Fstih Mudzaky
 * 3. Yedija Lewi Suryadi
 * 4. Zahra Mufidah
 */

public class kuesionerPanel1 extends javax.swing.JFrame {
    private boolean memilikiKantorPusat = false;
    private boolean kenaValidasi;
    private boolean memilikiGroupPerusahaan = false;
    private String namaPetugas;
    private DataPerkebunan dataPerkebunan;
    /**
     * Creates new form MainFrameKelompok2
     */
    public kuesionerPanel1(String namaPetugas, boolean kenaValidasi, DataPerkebunan dataPerkebunan) {
        initComponents();
        this.namaPetugas = namaPetugas;
        this.kenaValidasi = kenaValidasi;
        this.dataPerkebunan = dataPerkebunan;
        
        //Jika terkena validasi
        if (kenaValidasi) {
            setField();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat_perusahaanTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        kode_pos_perusahaanTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telepon_perusahaanTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email_perusahaanTextField = new javax.swing.JTextField();
        fax_perusahaanTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kab_kota_kode_perusahaanTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kecamatan_kode_perusahaanTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        desa_kelurahan_kode_perusahaanTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nama_picTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jabatan_picTextField = new javax.swing.JTextField();
        unit_kerja_picTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        telepon_picTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        laki_lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        status_perusahaanComboBox = new javax.swing.JComboBox<>();
        nextToggleButton = new javax.swing.JToggleButton();
        nama_perusahaanTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lintang_perusahaanTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        bujur_perusahaanTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        kbli_perusahaanTextField = new javax.swing.JTextField();
        provinsi_kode_perusahaanTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        memiliki_kantor_pusatCheckBox = new javax.swing.JCheckBox();
        memiliki_group_perusahaanCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1. Nama Perusahaan/Kantor Administratur:");

        jLabel2.setText("Alamat:");

        alamat_perusahaanTextArea.setColumns(20);
        alamat_perusahaanTextArea.setRows(5);
        jScrollPane1.setViewportView(alamat_perusahaanTextArea);

        jLabel3.setText("Kode Pos:");

        kode_pos_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_pos_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Telepon:");

        telepon_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telepon_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Email:");

        email_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_perusahaanTextFieldActionPerformed(evt);
            }
        });

        fax_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fax_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Fax:");

        jLabel9.setText("Provinsi:");

        jLabel10.setText("Kabupaten/Kota:");

        kab_kota_kode_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kab_kota_kode_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Kecamatan:");

        kecamatan_kode_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kecamatan_kode_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Desa/Kelurahan:");

        desa_kelurahan_kode_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desa_kelurahan_kode_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("Nama PIC:");

        nama_picTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_picTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Jabatan PIC:");

        jabatan_picTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatan_picTextFieldActionPerformed(evt);
            }
        });

        unit_kerja_picTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unit_kerja_picTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Unit Kerja PIC:");

        jLabel16.setText("HP/Telepon:");

        telepon_picTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telepon_picTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setText("Jenis Kelamin:");

        buttonGroup1.add(laki_lakiRadioButton);
        laki_lakiRadioButton.setText("Laki-Laki");

        buttonGroup1.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");

        jLabel18.setText("Status:");

        status_perusahaanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tutup", "Tutup Sementara" }));
        status_perusahaanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_perusahaanComboBoxActionPerformed(evt);
            }
        });

        nextToggleButton.setText("NEXT");
        nextToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextToggleButtonActionPerformed(evt);
            }
        });

        nama_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Koordinat Lokasi Perusahaan:");

        jLabel19.setText("Lintang:");

        lintang_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lintang_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setText("Bujur:");

        bujur_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bujur_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel21.setText("KBLI:");

        kbli_perusahaanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbli_perusahaanTextFieldActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("PENGENALAN TEMPAT");

        memiliki_kantor_pusatCheckBox.setText("Memiiki Kantor Pusat");
        memiliki_kantor_pusatCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memiliki_kantor_pusatCheckBoxActionPerformed(evt);
            }
        });

        memiliki_group_perusahaanCheckBox.setText("Memiiki Group Perusahaan");
        memiliki_group_perusahaanCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memiliki_group_perusahaanCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jabatan_picTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(unit_kerja_picTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(perempuanRadioButton)
                                                    .addComponent(laki_lakiRadioButton)
                                                    .addComponent(telepon_picTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(telepon_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fax_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(nextToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(status_perusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama_picTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kode_pos_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(provinsi_kode_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kab_kota_kode_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(desa_kelurahan_kode_perusahaanTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kecamatan_kode_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(memiliki_kantor_pusatCheckBox)
                            .addComponent(memiliki_group_perusahaanCheckBox)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lintang_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bujur_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kbli_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(244, 244, 244))))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nama_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(telepon_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(kode_pos_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(email_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(fax_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telepon_picTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(laki_lakiRadioButton)
                            .addComponent(jLabel17))
                        .addGap(3, 3, 3)
                        .addComponent(perempuanRadioButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provinsi_kode_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(kab_kota_kode_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(kecamatan_kode_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(desa_kelurahan_kode_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(nama_picTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jabatan_picTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(unit_kerja_picTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(status_perusahaanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lintang_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bujur_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kbli_perusahaanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memiliki_kantor_pusatCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memiliki_group_perusahaanCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextToggleButton)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kode_pos_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_pos_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_pos_perusahaanTextFieldActionPerformed

    private void telepon_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telepon_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telepon_perusahaanTextFieldActionPerformed

    private void email_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_perusahaanTextFieldActionPerformed

    private void fax_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fax_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fax_perusahaanTextFieldActionPerformed

    private void kab_kota_kode_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kab_kota_kode_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kab_kota_kode_perusahaanTextFieldActionPerformed

    private void kecamatan_kode_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kecamatan_kode_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kecamatan_kode_perusahaanTextFieldActionPerformed

    private void desa_kelurahan_kode_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desa_kelurahan_kode_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desa_kelurahan_kode_perusahaanTextFieldActionPerformed

    private void nama_picTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_picTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_picTextFieldActionPerformed

    private void jabatan_picTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatan_picTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatan_picTextFieldActionPerformed

    private void unit_kerja_picTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unit_kerja_picTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unit_kerja_picTextFieldActionPerformed

    private void telepon_picTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telepon_picTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telepon_picTextFieldActionPerformed

    private void nama_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_perusahaanTextFieldActionPerformed

    private void lintang_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lintang_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lintang_perusahaanTextFieldActionPerformed

    private void bujur_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bujur_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bujur_perusahaanTextFieldActionPerformed

    private void kbli_perusahaanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbli_perusahaanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbli_perusahaanTextFieldActionPerformed

    private void status_perusahaanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_perusahaanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_perusahaanComboBoxActionPerformed

    private void memiliki_kantor_pusatCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memiliki_kantor_pusatCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memiliki_kantor_pusatCheckBoxActionPerformed

    private void nextToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextToggleButtonActionPerformed
        // TODO add your handling code here
        //PERUSAHAAN
        dataPerkebunan.getPerusahaan().setNama(nama_perusahaanTextField.getText());
        dataPerkebunan.getPerusahaan().getAlamat().setAlamatLengkap(alamat_perusahaanTextArea.getText());
        dataPerkebunan.getPerusahaan().getAlamat().setKodePos(kode_pos_perusahaanTextField.getText());
        dataPerkebunan.getPerusahaan().getAlamat().setTelepon(telepon_perusahaanTextField.getText());
        dataPerkebunan.getPerusahaan().getAlamat().setEmail(email_perusahaanTextField.getText());
        dataPerkebunan.getPerusahaan().getAlamat().setFax(fax_perusahaanTextField.getText());
        dataPerkebunan.getPerusahaan().getAlamat().setProv(provinsi_kode_perusahaanTextField.getText());
        dataPerkebunan.getPerusahaan().getAlamat().setKabKota(kab_kota_kode_perusahaanTextField.getText());
        dataPerkebunan.getPerusahaan().setKecamatan(kecamatan_kode_perusahaanTextField.getText());
        dataPerkebunan.getPerusahaan().setDesaKel(desa_kelurahan_kode_perusahaanTextField.getText());
        dataPerkebunan.getPerusahaan().setNamaPIC(nama_picTextField.getText());
        dataPerkebunan.getPerusahaan().setTelpPIC(telepon_picTextField.getText());
        dataPerkebunan.getPerusahaan().setJabatanPIC(jabatan_picTextField.getText());
        if(laki_lakiRadioButton.isSelected()){
            dataPerkebunan.getPerusahaan().setJK_PIC('1');
        }
        if(perempuanRadioButton.isSelected()){
            dataPerkebunan.getPerusahaan().setJK_PIC('2');
        }
        dataPerkebunan.getPerusahaan().setUnitKerjaPIC(unit_kerja_picTextField.getText());
        dataPerkebunan.getPerusahaan().setStatus(status_perusahaanComboBox.getSelectedItem().toString());
        dataPerkebunan.getPerusahaan().setLintang(Double.parseDouble(lintang_perusahaanTextField.getText()));
        dataPerkebunan.getPerusahaan().setBujur(Double.parseDouble(bujur_perusahaanTextField.getText()));
        dataPerkebunan.getPerusahaan().setKBLI(kbli_perusahaanTextField.getText());
        
        memilikiKantorPusat = memiliki_kantor_pusatCheckBox.isSelected();
        memilikiGroupPerusahaan = memiliki_group_perusahaanCheckBox.isSelected();
        kuesionerPanel1b panel1b = new kuesionerPanel1b(namaPetugas, kenaValidasi, memilikiKantorPusat, memilikiGroupPerusahaan, dataPerkebunan);
        panel1b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nextToggleButtonActionPerformed

    private void memiliki_group_perusahaanCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memiliki_group_perusahaanCheckBoxActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_memiliki_group_perusahaanCheckBoxActionPerformed

    private void setField(){
        nama_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getNama());
        alamat_perusahaanTextArea.setText(dataPerkebunan.getPerusahaan().getAlamat().getAlamatLengkap());
        kode_pos_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getAlamat().getKodePos());
        telepon_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getAlamat().getTelepon());
        email_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getAlamat().getEmail());
        fax_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getAlamat().getFax());
        provinsi_kode_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getAlamat().getProv());
        kab_kota_kode_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getAlamat().getKabKota());
        kecamatan_kode_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getKecamatan());
        desa_kelurahan_kode_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getDesaKel());
        nama_picTextField.setText(dataPerkebunan.getPerusahaan().getNamaPIC());
        telepon_picTextField.setText(dataPerkebunan.getPerusahaan().getTelpPIC());
        jabatan_picTextField.setText(dataPerkebunan.getPerusahaan().getJabatanPIC());
        if(dataPerkebunan.getPerusahaan().getJK_PIC() == '1'){
            laki_lakiRadioButton.setSelected(true);
        }else{
            perempuanRadioButton.setSelected(true);
        }
        unit_kerja_picTextField.setText(dataPerkebunan.getPerusahaan().getUnitKerjaPIC());
        if(dataPerkebunan.getPerusahaan().getStatus().equalsIgnoreCase("aktif")){
            status_perusahaanComboBox.setSelectedIndex(0);
        }
        else if(dataPerkebunan.getPerusahaan().getStatus().equalsIgnoreCase("tutup")){
            status_perusahaanComboBox.setSelectedIndex(1);
        }
        else{
            status_perusahaanComboBox.setSelectedIndex(2);
        }
        lintang_perusahaanTextField.setText(Double.toString(dataPerkebunan.getPerusahaan().getLintang()));
        bujur_perusahaanTextField.setText(Double.toString(dataPerkebunan.getPerusahaan().getBujur()));
        kbli_perusahaanTextField.setText(dataPerkebunan.getPerusahaan().getKBLI());
        memiliki_kantor_pusatCheckBox.setSelected(!(dataPerkebunan.getKantorPusat() == null));
        memiliki_group_perusahaanCheckBox.setSelected(!(dataPerkebunan.getGroupPerusahaan() == null));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String namaPetugas = null;
        boolean kenaValidasi = false;
        DataPerkebunan dataPerkebunan = null;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kuesionerPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kuesionerPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kuesionerPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kuesionerPanel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kuesionerPanel1(namaPetugas, kenaValidasi, dataPerkebunan).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat_perusahaanTextArea;
    private javax.swing.JTextField bujur_perusahaanTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField desa_kelurahan_kode_perusahaanTextField;
    private javax.swing.JTextField email_perusahaanTextField;
    private javax.swing.JTextField fax_perusahaanTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jabatan_picTextField;
    private javax.swing.JTextField kab_kota_kode_perusahaanTextField;
    private javax.swing.JTextField kbli_perusahaanTextField;
    private javax.swing.JTextField kecamatan_kode_perusahaanTextField;
    private javax.swing.JTextField kode_pos_perusahaanTextField;
    private javax.swing.JRadioButton laki_lakiRadioButton;
    private javax.swing.JTextField lintang_perusahaanTextField;
    private javax.swing.JCheckBox memiliki_group_perusahaanCheckBox;
    private javax.swing.JCheckBox memiliki_kantor_pusatCheckBox;
    private javax.swing.JTextField nama_perusahaanTextField;
    private javax.swing.JTextField nama_picTextField;
    private javax.swing.JToggleButton nextToggleButton;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JTextField provinsi_kode_perusahaanTextField;
    private javax.swing.JComboBox<String> status_perusahaanComboBox;
    private javax.swing.JTextField telepon_perusahaanTextField;
    private javax.swing.JTextField telepon_picTextField;
    private javax.swing.JTextField unit_kerja_picTextField;
    // End of variables declaration//GEN-END:variables
}
