/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mform.PanelData;

import javax.swing.JScrollPane;

import mform.DataKuesioner;
import mform.PemeriksaPanel;
import mform.entity.Kebun;

/**
 *
 * @author fatih
 */
public class Panel3duplikat extends javax.swing.JPanel {
    JScrollPane pane = null;
    private Panel3duplikat[] panel3duplikat; 

    public static Kebun[] kebuns = new Kebun[PemeriksaPanel.dataPerkebunan.getJumlahKebun()];
    private Kebun kebun;
    /**
     * Creates new form Panel3duplikat
     */
    public Panel3duplikat(JScrollPane pane) {
        this.pane = pane;
        kebuns[DataKuesioner.indexPanel] = PemeriksaPanel.dataPerkebunan.getKebun(DataKuesioner.indexPanel);
        kebun = PemeriksaPanel.dataPerkebunan.getKebun(DataKuesioner.indexPanel);
        initComponents();
        judulLabel.setText("LUAS TANAMAN DAN PRODUKSI KEBUN KE-" + (DataKuesioner.indexPanel + 1));
        setField();
    }

    public Panel3duplikat[] getPanel3duplikat() {
        return panel3duplikat;
    }

    public void setPanel3duplikat(Panel3duplikat[] panel3duplikat) {
        this.panel3duplikat = panel3duplikat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        provTextField = new javax.swing.JTextField();
        judulLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rendemenHablurTextField = new javax.swing.JTextField();
        kabKotaTextField = new javax.swing.JTextField();
        luasTebangTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        panel3SaveButton = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        hablurTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tetesTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        luasTanamTextField = new javax.swing.JTextField();
        jenisKebunComboBox = new javax.swing.JComboBox<>();
        gkpTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tebuTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();

        judulLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        judulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLabel.setText("LUAS TANAMAN DAN PRODUKSI");

        jLabel12.setText("Rendemen Hablur (%): ");

        jLabel11.setText("Hablur: ");

        panel3SaveButton.setText("SAVE CHANGE");
        panel3SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panel3SaveButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Kabupaten/Kota:");

        jLabel8.setText("Tetes: ");

        jLabel4.setText("Luas Areal Tebang (Ha): ");

        jLabel9.setText("Provinsi:");

        jLabel7.setText("GKP:");

        jenisKebunComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tebu Sendiri", "Tebu Rakyat", "Pembelian dari Pihak Ketiga" }));

        jLabel6.setText("Tebu:");

        jLabel3.setText("Luas Areal Tanam (Ha): ");

        jLabel1.setText("Jenis Kebun:");

        jLabel5.setText("Produksi (Ton):");

        nextButton.setText("NEXT");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(luasTanamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(luasTebangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tebuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gkpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tetesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hablurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rendemenHablurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jenisKebunComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kabKotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel3SaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton)
                .addContainerGap())
            .addComponent(judulLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jenisKebunComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(provTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kabKotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(luasTanamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(luasTebangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tebuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gkpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tetesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(hablurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rendemenHablurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(panel3SaveButton)
                    .addComponent(nextButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panel3SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panel3SaveButtonActionPerformed
        save();
    }//GEN-LAST:event_panel3SaveButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        save();
        System.out.println(DataKuesioner.indexPanel);
        DataKuesioner.indexPanel++;

        if(DataKuesioner.indexPanel > PemeriksaPanel.dataPerkebunan.getJumlahKebun()-1){
            DataKuesioner.indexPanel = 0;
        }
        try {
            pane.setViewportView(panel3duplikat[DataKuesioner.indexPanel]);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void setField(){
        //Jenis kebun
        switch (kebun.getJenisKebun().toLowerCase()) {
            case "tebu sendiri" -> jenisKebunComboBox.setSelectedIndex(0);
            case "tebu rakyat" -> jenisKebunComboBox.setSelectedIndex(1);
            case "pembelian dari pihak ketiga" -> jenisKebunComboBox.setSelectedIndex(2);
            default -> jenisKebunComboBox.setSelectedIndex(0);
        }
        
        //Letak: provinsi, kab/kota
        provTextField.setText(kebun.getLetak().getProv());
        kabKotaTextField.setText(kebun.getLetak().getKabKota());
        
        //Luas
        luasTanamTextField.setText(Double.toString(kebun.getLuasArealTanam()));
        luasTebangTextField.setText(Double.toString(kebun.getProduksi().getLuasArealTebang()));

        //Produksi
        tebuTextField.setText(Double.toString(kebun.getProduksi().getProduksiTebu()));
        gkpTextField.setText(Double.toString(kebun.getProduksi().getProduksiTetes()));
        tetesTextField.setText(Double.toString(kebun.getProduksi().getProduksiTetes()));
        hablurTextField.setText(Double.toString(kebun.getProduksi().getProduksiHablur()));
        rendemenHablurTextField.setText(Double.toString(kebun.getProduksi().getRendemenHablur()));
    }

    private void save() {
        // Jenis kebun
        switch (jenisKebunComboBox.getSelectedIndex()) {
            case 0 -> kebun.setJenisKebun("Tebu Sendiri");
            case 1 -> kebun.setJenisKebun("Tebu Rakyat");
            case 2 -> kebun.setJenisKebun("Pembelian dari Pihak Ketiga");
            default -> kebun.setJenisKebun("");
        }
    
        // Letak: provinsi, kab/kota
        kebun.getLetak().setProv(provTextField.getText());
        kebun.getLetak().setKabKota(kabKotaTextField.getText());
    
        // Luas
        try {
            kebun.setLuasArealTanam(Double.parseDouble(luasTanamTextField.getText()));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    
        try {
            kebun.getProduksi().setLuasArealTebang(Double.parseDouble(luasTebangTextField.getText()));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    
        // Produksi
        try {
            kebun.getProduksi().setProduksiTebu(Double.parseDouble(tebuTextField.getText()));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    
        try {
            kebun.getProduksi().setProduksiGKP(Double.parseDouble(gkpTextField.getText()));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    
        try {
            kebun.getProduksi().setProduksiTetes(Double.parseDouble(tetesTextField.getText()));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    
        try {
            kebun.getProduksi().setProduksiHablur(Double.parseDouble(hablurTextField.getText()));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    
        try {
            kebun.getProduksi().setRendemenHablur(Double.parseDouble(rendemenHablurTextField.getText()));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }

        kebuns[DataKuesioner.indexPanel] = kebun;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gkpTextField;
    private javax.swing.JTextField hablurTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jenisKebunComboBox;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTextField kabKotaTextField;
    private javax.swing.JTextField luasTanamTextField;
    private javax.swing.JTextField luasTebangTextField;
    private javax.swing.JButton nextButton;
    public javax.swing.JToggleButton panel3SaveButton;
    private javax.swing.JTextField provTextField;
    private javax.swing.JTextField rendemenHablurTextField;
    private javax.swing.JTextField tebuTextField;
    private javax.swing.JTextField tetesTextField;
    // End of variables declaration//GEN-END:variables
}
